### ISSUE TITLE
Header menu links

### ISSUE THREAD

**Issue by Youdaman** [Youdaman/clemenger#1]
·  The header menu needs to have (Junction | Intranet | Careers) – Junction is missing, Careers doesn’t open up the popup like the current page, these links should be in the top right of screen in smaller font

**Comment by Youdaman** [comment]
Need the URLs for those three

**Comment by Youdaman** [comment]
Comment in moqups:

> Intranet links to intranet.cfmrs.com.au

> Junction links to creativeactivationjunction.com.au

> careers launches pop up about joining our team - links to our subscribe-hr page

**Comment by Youdaman** [comment]
> careers launches pop up about joining our team - links to our subscribe-hr page

Need more info about how this popup looks and/or the link to the "subscribe-hr" page

**Comment by ernestfitzgerald** [comment]
Hi mate - if you look at the current site, when clicking on careers it pops up with a message and a link to: https://creativefieldmarketing.jobs.subscribe-hr.com/

We would like to keep this except with one change - There should be an additional button underneath that says "Sign Up as a Mystery SHopper" which links them (for now) to: creativeactivationjunction.com.au

**Comment by Youdaman** [comment]
Thanks Ernest, didn't think to check the old site! No worries, will see what I can do
