### ISSUE TITLE
Video links

### ISSUE THREAD

**Issue by Youdaman** [Youdaman/clemenger#29]
Video company provided private Vimeo links, links need to be public.

Ernest/Michael are going to put them on the Clemenger YouTube or possibly the intranet however the links need to be unlisted/public and not private

**Comment by ernestfitzgerald** [comment]
Is there anyway of downloading these and hosting them along with the website as opposed to using vimeo or youtube?

CA Highlight v2 - https://urldefense.proofpoint.com/v2/url?u=https-3A__vimeo.com_472050397_a6a3acf8a3&d=DwMFaQ&c=HdAUNv_EOZyljLc1cjbHCq-Eo7r1kRHoywhQbi81uaA&r=A4x-rQS0n7oDp1LxZZj3-IfyG7CycX8lWvqgmV0A2jzWn_28pUvGbNMl8pZT1uyZ&m=yB41d203pOeOXGywwRwJ7uboCxuLiWtpnbg_20LaiZo&s=_HMqN8hIGzfz3SYMgVJjW_qOtwZkpR1P2VPhRl2uo_I&e=

CFM Highlight v2 - https://urldefense.proofpoint.com/v2/url?u=https-3A__vimeo.com_472049171_55741a25bd&d=DwMFaQ&c=HdAUNv_EOZyljLc1cjbHCq-Eo7r1kRHoywhQbi81uaA&r=A4x-rQS0n7oDp1LxZZj3-IfyG7CycX8lWvqgmV0A2jzWn_28pUvGbNMl8pZT1uyZ&m=yB41d203pOeOXGywwRwJ7uboCxuLiWtpnbg_20LaiZo&s=g5rfC_doFRBFcKUzctjkPEZkM2BkoAE2ogwEGP3THG4&e=

**Comment by Youdaman** [comment]
Yes they can be put on your hosting and linked to instead of using Vimeo/YouTube.

Will show you how to do the link tomorrow.
