### ISSUE TITLE
CGLRS - Look & Feel

### ISSUE THREAD

**Issue by ernestfitzgerald** [Youdaman/clemenger#50]
Are we able to recreate the look of the body of the page for CGLRS as per the moqup?

Its a light grey background with white tiles with rounded edges hovering over the top that holds the body of each header and copy? Kinda like the facebook website?

Let me know if you need more clarification to what i mean

**Comment by Youdaman** [comment]
I'll have to rework the underlying boxes (the current structure doesn't allow for separate borders/background) but yes can do.

**Comment by Youdaman** [comment]
Done.
