### ISSUE TITLE
Contact form dynamic recipients

### ISSUE THREAD

**Issue by Youdaman** [Youdaman/clemenger#52]
Configure forms to send to different emails depending on which option is selected in a dropdown

**Comment by Youdaman** [comment]
Purchased a license for the premium version, need details from Ernest/Melissa about recipients + option dropdown to trigger

**Comment by Youdaman** [comment]
Need options for the dropdown and the associated emails for each please

**Comment by ernestfitzgerald** [comment]
Hi mate:
"**Enquiry Type**" ***Mandatory field (include this dropdown in the email push)***:
"Current employee enquiry - Field team or office staff" > goes to hr.helpdesk@cglrs.com.au
"Current employee enquiry - Mystery shoppers and auditors" > goes to thejunction.operations@creativeactivation.com.au
"Looking to join the team" > goes to recruitment@cglrs.com.au
"New business opportunity":  goes to > CA.Enquiries@creativeactivation.com.au, CC: ernest.fitzgerald@creativeactivation.com.au and nancy.commins@cglrs.com.au
"Other": goes to > CA.Enquiries@creativeactivation.com.au

These are typically pushed out from noreply@creativeactivation.com.au to the above boxes

**Comment by Youdaman** [comment]
![screencapture-clemenger-local-ca-wp-admin-admin-php-2020-11-12-16_35_55](https://user-images.githubusercontent.com/287330/98900188-5705e380-2505-11eb-9ba8-457af7690bed.jpg)

Attached is a screenshot of the configuration for the CA form, this has been duplicated for CFM and CGLRS (and the subject lines for the notification emails changed to match, e.g. "CGLRS Enquiry" if from CGLRS etc)
