### ISSUE TITLE
Privacy Policies

### ISSUE THREAD

**Issue by ernestfitzgerald** [Youdaman/clemenger#54]
Can you link all privacy policy links to here:
https://www.clemenger.com.au/attachments/Clemenger_Group_Privacy_Policy.pdf

Can you also change the copyright on each page to their respective brands;

Creative Activation 
Clemenger Field Marketing 
Clemenger Group Limited Retail Services

as they currently all say (c) Creative Activation

**Comment by Youdaman** [comment]
Done, will upload soon
