### ISSUE TITLE
ClemsFM Site Fixes

### ISSUE THREAD

**Issue by ernestfitzgerald** [Youdaman/clemenger#55]
Hi - can you please make the following fixes:

1. All font should match the style guide (attached in dropbox (ClemsFMBrandGuidelines.pdf) which is ITC Franklin Gothic (Demi for headings) (book for body of copy) can we also ensure all the uppercase font is returned to sentence case in this page (uppercase is for CA only)
2. On the header "Get in touch" seems to be in a different colour to the other links on my computer - Also when you mouse_over the first three links they dont change colour like the last three links in the header - just need to review the consistency
3. The Careers popup is styled after CA - can we change this to be a white background with the clemengerfm logo instead of the CA logo?
4. The copy on the first two splash pages "We're not the partner...." and "Clemenger Field Marketing is driven..." Can we match the font size, shadow, etc to ensure both are the same and make them both match the style guide
5. On the Our Services - other than matching the style guide, is there anyway to make it look more like a button on the accordion? So people know where to click
6. The blog has horizontal scroll on all the tiles for some reason - can we remove that?
7. There was a section before with our people - and it had the group photo of all 4 of the team, what happened to that? Can we also add it to the header as a link?

**Comment by ernestfitzgerald** [comment]
One more thing - I love the way the tiles for every part of the page now looks on the CGLRS page (the tile with the rounded edges sitting on top of a grey background) could we do that for the clemsFM page too? Starting at the "Our Services" part? It looks cool!

**Comment by Youdaman** [comment]
Created 8 new issues, closing this one
