### ISSUE TITLE
CGLRS Site Fixes

### ISSUE THREAD

**Issue by ernestfitzgerald** [Youdaman/clemenger#56]
Hi mate for this site can we:

1. Match the style guide thats in drop box? Font (Archivo) colours, etc? Also - we need to use proper sentence case on this site so any capitals should be replaced
2. Our Brands - Where the two tiles are for both brands, can we shrink the tile and contents by about 20% here? they look a bit too big - can we also link each tile to their respective websites when you click on them? Also - lets replace the uppercase to sentence case for both brand tiles here in the copy
3. Our people - the new copy is on the moqups, can you copy and paste each persons blurb?

**Comment by Youdaman** [comment]
Created 3 new issues, closing this one
