### ISSUE TITLE
CA Site Fixes

### ISSUE THREAD

**Issue by ernestfitzgerald** [Youdaman/clemenger#57]
Hi mate can we make the following changes:

1. The six rotating tiles - can we just slightly reduce their size by about 10-15%?
2. Our services tiles - can we add a slight drop shadow to each of the outside of the 4 tiles?
3. I messed up the colours on the our people photos for: Chris Modowski, Nicole James, Joanne Beehag and Kim Harrison - i've uploaded the new ones to the drop box are you able to quickly replace them?
4. Also - on our people, for each tile can we use uppercase for each persons name and their job title?
5. Our news - these also have the wierd horizontal scroll bars on the tiles can we remove that? Also - at the top the link says "BLOG" it should say "OUR NEWS"

**Comment by Youdaman** [comment]
Created 5 new issues, closing this one
