### ISSUE TITLE
People CA

### ISSUE THREAD

**Issue by Youdaman** [Youdaman/clemenger#6]
looks fine just need to play with the copy, linked in links and sizes

**Comment by Youdaman** [comment]
Need a list of everyone's name (some I have, some I don't) and a link to their respective LinkedIn profiles please

**Comment by Youdaman** [comment]
I can grab most of the names/links from the existing site http://creativeactivation.com.au/#!/people but there might be some leftover so those are the only ones I'll need

**Comment by Youdaman** [comment]
Also Nancy's last name and role don't match in the mockup vs old site so I'll need clarification there -- along with any missing

**Comment by Youdaman** [comment]
Waiting on Ernest to send copy/images/linkedin/names

**Comment by Youdaman** [comment]
Have details for all but a few, just waiting on those

**Comment by ernestfitzgerald** [comment]
These should be all updated now in the dropbox
