### ISSUE TITLE
Channels CA/CFM

### ISSUE THREAD

**Issue by Youdaman** [Youdaman/clemenger#8]
I’m 50/50 on displaying it this way, I think I prefer the grid, if it is in this linear format it needs to be spaced properly/sized

**Comment by Youdaman** [comment]
Might need sharper logos?

**Comment by Youdaman** [comment]
Waiting on logos from Ernest

**Comment by ernestfitzgerald** [comment]
Sharper logos now added to the dropbox folder

**Comment by Youdaman** [comment]
I can see the new folder Website Assets\Retailer Logos 

Note: the Harvey_Norman-Logo.wine file is broken

Do you want all 24 logos on both sites?

**Comment by ernestfitzgerald** [comment]
Yes - same logos on both sites

**Comment by ernestfitzgerald** [comment]
Harvey norman updated
